# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The frontend guide to life, universe and everything
date: 15<sup>th</sup> and 16<sup>th</sup> September <span>—</span> Bologna, Italy
email: matteo@fromthefront.it
description: >
  The frontend guide to life, universe and everything is going to be an inspiring, formative, cutting edge gathering of  some of the best frontend developers and UX people in the world. Bologna, september 2016
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://2016.fromthefront.it" # the base hostname & protocol for your site
twitter_username: fromthefront
github_username:  mattcav

# Build settings
markdown: kramdown
sass:
  style: :compressed
