# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The frontend guide to life, universe and everything
date: 15<sup>th</sup> and 16<sup>th</sup> September Bologna, Italy
email: matteo@fromthefront.it
description: >
  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima quisquam veniam tempora incidunt quos excepturi at explicabo, animi a dignissimos sunt natus libero id officia neque iure deserunt, magni molestiae!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://2016.fromthefront.it" # the base hostname & protocol for your site
twitter_username: fromthefront
github_username:  mattcav

# Build settings
markdown: kramdown
sass:
  style: :compressed
